### PR TITLE
promoteDebugAsInfo feature, fix #8

### LINKED ISSUE #8: Display output depending on a settings
It would be very useful to have Ansible output processed on maven output to monitor what happens during the process.
Right now the output is available with the "--debug" maven flag which turns the whole maven into debug mode, too much verbosity, I'd like only Ansible to be verbose =)

In AbstractAnsibleMojo.java, there is this line of code
```
getLog().debug(outputLine);
```

Could it be possible to change verbosity depending on a plugin settings, for example ansible.promoteDebugAsInfo ?
In that case, code could be :
```
if (promoteDebugAsInfo) {
    getLog().info(outputLine);
} else {
    getLog().debug(outputLine);
}
```

### PR DESCRIPTION
**Pull request by astik**

### CODE REVIEW

**Comment by tmullender** [comment]
Hey Romain, 

Thanks for the input, it's something I've thought about a couple of times but always just lived with the logDirectory option.

Implementation looks good, can you add a test though in src/it as an example and to show that it works?

**Comment by astik** [comment]
I'll look into adding testes ...
I have to admit, right now, I have no idea how to make it though =/

**Comment by astik** [comment]
Unit tests have been pushed.
I reused your 3 simple-ansible-* test in which I add the check for INFO log level.
I didn't change your original test, I don't know if you wanted or not to check on the log level to assure that it was a DEBUG by default.

**Comment by tmullender** [comment]
I've removed the debug logging for those tests, which ensures that the line is being logged at a higher level and merged the changes into master

The snapshot is available in the sonatype repository, I'll aim to release it around the end of the month

**Comment by astik** [comment]
Hi,
Any idea on when the plugin will be released as a stable version ?
Thanks in advance

**Comment by tmullender** [comment]
Hey Romain,

1.2.0 was released at the end of March and contained this feature.  Have you tried using it?

Tim

**Comment by astik** [comment]
Indeed, i missed the update. It works like a charm !
Still, there is no tag into Git for this version, am I missing something ?
Anyway, thanks for this release, it will help me a lot to debug faulty processes =)

**Pull request closed without merging**
