### PR TITLE
Making "ansible.syntaxCheck" property (ansible-playbook --syntax-check )

### PR DESCRIPTION
**Pull request by andrei-kolosok**

### CODE REVIEW

**Comment by tmullender** [comment]
Hi Andrei

Thanks for the contribution.  Before I merge it in could you add a test to show how this is used and check that it works?  See src/it for the existing tests if you want an example.

**Comment by andrei-kolosok** [comment]
Hi Tim,

Could you pls check the last commits?

I've added 2 types of test:
- syntaxCheck option via command line args
- syntaxCheck option via pom file configuration

and also description to README.md

**Comment by tmullender** [comment]
Hi Andrei

Commits merged.  Let me know if you need this released soon if not I might try and make a few more updates.

Tim

**Comment by andrei-kolosok** [comment]
Hi Tim,

Great!

Well, it would be nice to have it soon, we'd like to include this check to
out CI-process.
But it can wait couple of weeks, it's a plan for our next sprint.

Best regards
Andrei Kalasok

2016-08-13 10:24 GMT+02:00 Tim Mullender <notifications@github.com>:

**Comment by tmullender** [comment]
Released in 1.3.0

**Comment by andrei-kolosok** [comment]
Thanks a lot Tim!

Best regards
Andrei Kalasok

2016-08-14 14:43 GMT+02:00 Tim Mullender <notifications@github.com>:

**Pull request merged**
